#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11
TOTAL_MINUTES=136
ENV_FILE="${ENV_FILE:-/tmp/discord-clone-private-alpha.env}"
umask 077

banner "DiscordClone private-alpha voice deployment"

stage "Confirm the no-bill boundary" 5
say "This guide is for your AWS Free account plan. Do not click Upgrade plan."
open_url "https://console.aws.amazon.com/billing/home"
step "Confirm the Cost and usage card says credits cover your free-plan costs."
step "Open Budgets, create the Zero spend budget template, and add your email."
step "Return to the AWS Console home. Keep the region set to Europe (Stockholm)."
warn "Budgets are alerts; the Free plan—not the alert—is what prevents pay-as-you-go billing."
pause "Press Enter only after the budget email subscription is confirmed."

stage "Confirm the external names and TURN key" 10
say "Your HTTPS hostname is already created: voiceechattest.duckdns.org."
ask PHX_HOST "Confirm the hostname [voiceechattest.duckdns.org]:"
[[ -z "$PHX_HOST" ]] && PHX_HOST="voiceechattest.duckdns.org"
write_env PHX_HOST "$PHX_HOST"
open_url "https://dash.cloudflare.com/"
step "Open Realtime → TURN. Open the TURN key you created."
step "Copy its TURN Token ID / key ID. Do not copy or use a temporary browser credential."
ask CLOUDFLARE_TURN_KEY_ID "Paste the TURN key ID:"
write_env CLOUDFLARE_TURN_KEY_ID "$CLOUDFLARE_TURN_KEY_ID"
step "Copy the long-lived API token for that TURN key. It belongs only on the VM."
ask_secret CLOUDFLARE_TURN_API_TOKEN "Paste the TURN API token (hidden):"
write_env CLOUDFLARE_TURN_API_TOKEN "$CLOUDFLARE_TURN_API_TOKEN"
warn "This temporary file is mode 600. Delete it after copying the values to the VM. Never commit it."
pause "Press Enter when both values were captured."

stage "Launch the ARM64 VM" 15
open_url "https://eu-north-1.console.aws.amazon.com/ec2/home?region=eu-north-1#Instances:"
step "Choose Launch instances and name it discord-clone-alpha."
step "Choose Ubuntu Server 24.04 LTS, 64-bit (Arm), from Canonical. Do not choose an AWS Marketplace image."
step "Choose instance type t4g.small. In Advanced details set Credit specification to Standard."
step "Create a new key pair: RSA, .pem. Download it once and keep it private."
step "Create a security group named discord-clone-alpha with exactly: SSH TCP 22 from My IP; HTTP TCP 80 from Anywhere-IPv4; HTTPS TCP 443 from Anywhere-IPv4; Custom UDP 50000-50031 from Anywhere-IPv4."
step "Set storage to one 30 GiB gp3 volume. Launch one instance."
confirm "The instance details show t4g.small, 30 GiB gp3, and only the four intended inbound rules. Launch it now?" || exit 0
pause "Wait until Instance state is Running and Status check is 2/2 passed, then press Enter."

stage "Attach a stable public address" 10
open_url "https://eu-north-1.console.aws.amazon.com/ec2/home?region=eu-north-1#Addresses:"
step "Choose Allocate Elastic IP address → Allocate. Select the new address."
step "Actions → Associate Elastic IP address → Resource type Instance → select discord-clone-alpha → Associate."
step "Copy the Elastic IP and the instance Private IPv4 address from the instance Networking tab."
ask VOICE_EXTERNAL_IPV4 "Paste the Elastic IP:"
ask VOICE_INTERNAL_IPV4 "Paste the instance private IPv4:"
write_env VOICE_EXTERNAL_IPV4 "$VOICE_EXTERNAL_IPV4"
write_env VOICE_INTERNAL_IPV4 "$VOICE_INTERNAL_IPV4"
pause "Press Enter after the Elastic IP is associated."

stage "Point DuckDNS at the Elastic IP" 5
open_url "https://www.duckdns.org/"
step "Sign in. Under voiceechattest, replace the current IP with the Elastic IP you just allocated."
step "Click update. Wait one minute, then verify from your Mac: dig +short voiceechattest.duckdns.org"
pause "Press Enter only when dig returns the Elastic IP exactly."

stage "Prepare the VM and upload the source" 15
say "On your Mac, use the downloaded key and the Elastic IP. Connect first so we can install rsync and the build dependencies:"
say "chmod 400 /path/to/your-key.pem"
say "ssh -i /path/to/your-key.pem ubuntu@<ELASTIC_IP>"
step "Inside the VM, run the following commands one at a time:"
say "sudo apt update"
say "sudo apt install -y build-essential caddy elixir erlang-dev git postgresql postgresql-contrib rsync pkg-config libssl-dev libsrtp2-dev"
say "elixir --version"
step "Stop here if Elixir is older than 1.15; do not continue with an unsupported runtime."
say "exit"
step "Back on your Mac, copy the current local source to the VM. This avoids publishing secrets or relying on GitHub access:"
say "rsync -av --delete --exclude '.git' --exclude '_build' --exclude 'deps' --exclude 'node_modules' --exclude '.scratch' -e \"ssh -i /path/to/your-key.pem\" /Users/increment-tech-04/discord_clone/ ubuntu@<ELASTIC_IP>:/tmp/discord_clone_build/"
say "ssh -i /path/to/your-key.pem ubuntu@<ELASTIC_IP>"
say "sudo useradd --system --create-home --home-dir /var/lib/discord-clone --shell /usr/sbin/nologin discord-clone"
say "sudo install -d -o discord-clone -g discord-clone -m 0755 /opt/discord_clone"
pause "Press Enter after these commands succeed."

stage "Build the production release on ARM64" 15
say "Still on the VM, run:"
say "cd /tmp/discord_clone_build"
say "mix local.hex --force && mix local.rebar --force"
say "MIX_ENV=prod mix deps.get --only prod"
say "MIX_ENV=prod mix assets.deploy"
say "MIX_ENV=prod mix release"
step "If dependency compilation fails, copy the full error into this chat; do not switch instance type or enable paid services."
say "sudo rsync -a --delete _build/prod/rel/discord_clone/ /opt/discord_clone/"
say "sudo chown -R discord-clone:discord-clone /opt/discord_clone"
pause "Press Enter only after the release build and rsync both succeed."

stage "Create PostgreSQL and protected runtime configuration" 20
say "Choose a unique 32+ character password using only letters and numbers, so it is safe in a URL. Keep it in your password manager."
say "sudo -u postgres createuser --pwprompt discord_clone"
say "sudo -u postgres createdb --owner=discord_clone discord_clone_prod"
say "cd /tmp/discord_clone_build && mix phx.gen.secret"
step "Copy the secret printed by the last command. Then create the protected environment file:"
say "sudo touch /etc/discord-clone.env"
say "sudo chown root:discord-clone /etc/discord-clone.env"
say "sudo chmod 0640 /etc/discord-clone.env"
say "sudoedit /etc/discord-clone.env"
step "Enter exactly these lines, replacing only the bracketed values. Keep the Cloudflare token secret:"
say "PHX_HOST=voiceechattest.duckdns.org"
say "PORT=4000"
say "DATABASE_URL=postgres://discord_clone:[YOUR_ALPHANUMERIC_DB_PASSWORD]@localhost/discord_clone_prod"
say "SECRET_KEY_BASE=[OUTPUT_OF_MIX_PHX_GEN_SECRET]"
say "POOL_SIZE=5"
say "RELEASE_DISTRIBUTION=none"
say "VOICE_ICE_MODE=standard"
say "VOICE_STUN_URLS=stun:stun.cloudflare.com:3478"
say "VOICE_INTERNAL_IPV4=[INSTANCE_PRIVATE_IPV4]"
say "VOICE_EXTERNAL_IPV4=[ELASTIC_IP]"
say "VOICE_TURN_CREDENTIAL_TTL_SECONDS=86400"
say "CLOUDFLARE_TURN_KEY_ID=[TURN_KEY_ID]"
say "CLOUDFLARE_TURN_API_TOKEN=[TURN_API_TOKEN]"
say "PHX_SERVER=true"
warn "Do not paste this file, the database password, or the Cloudflare token into chat."
pause "Press Enter after saving and exiting sudoedit."

stage "Install services, migrate, and issue HTTPS" 15
say "Still on the VM, run:"
say "cd /tmp/discord_clone_build"
say "sudo install -o root -g root -m 0644 deploy/discord-clone.service.example /etc/systemd/system/discord-clone.service"
say "sudo sed 's/alpha\\.example\\.com/voiceechattest.duckdns.org/g' deploy/Caddyfile.example | sudo tee /etc/caddy/Caddyfile >/dev/null"
say "sudo systemctl daemon-reload"
say "sudo systemd-run --wait --pipe --collect --property=User=discord-clone --property=Group=discord-clone --property=WorkingDirectory=/opt/discord_clone --property=EnvironmentFile=/etc/discord-clone.env /opt/discord_clone/bin/migrate"
say "sudo caddy validate --config /etc/caddy/Caddyfile"
say "sudo systemctl enable --now discord-clone caddy"
say "sudo systemctl --no-pager --full status discord-clone caddy"
step "From your Mac, open https://voiceechattest.duckdns.org/healthz then /readyz. Both must return {\"status\":\"ok\"}."
pause "Press Enter only when both URLs work over HTTPS."

stage "Provision users and prove real-network voice" 15
say "On the VM, create each test user with the repository's safe release command in README.md."
step "Open the HTTPS site on two authenticated devices on different networks—for example home Wi-Fi and cellular. Join the same Voice Channel and prove audio both directions."
step "For the final relay proof only, change VOICE_ICE_MODE to turn_only in /etc/discord-clone.env, restart discord-clone, test briefly, then return it to standard and restart again."
say "sudo systemctl restart discord-clone"
step "Check AWS Billing and Cloudflare TURN analytics after the test."
warn "When testing is finished for a while, terminate the EC2 instance, delete its EBS volume, and release the Elastic IP. Stopping alone leaves storage and IP resources behind."

stage "Remove the temporary local secret cache" 1
say "After the VM is healthy, this Mac-side temporary file is no longer needed: $ENV_FILE"
if confirm "Delete that temporary file now?"; then
  rm -f "$ENV_FILE"
  say "Deleted $ENV_FILE"
else
  warn "Delete it yourself as soon as you have copied the TURN values into /etc/discord-clone.env."
fi

finish
